<a href="https://colab.research.google.com/github/Ayseguldeniz/bookstore-project/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [3]:
import numpy as np
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [4]:
samples = np.random.normal(100, 15, 1000)
samples

array([ 98.25927317,  86.33331955, 119.10846649,  91.55807183,
       108.87370488, 104.3350779 ,  97.84082549,  99.67587978,
       117.14318062, 131.55177303,  81.93056676, 100.37926166,
       100.30205382, 113.19856858,  88.00443177, 110.24317862,
       116.81915197, 104.57909016,  79.62553963,  83.06823111,
       119.44441377, 113.46488544,  95.2717922 , 116.54799051,
       101.6147828 , 110.57258873,  95.95523453,  94.16055721,
       112.54348941, 116.90162568,  99.04122666, 119.00198431,
        90.64087912, 104.58019996,  91.71404518,  99.93125018,
        89.30875452,  90.46573065, 110.67733899,  95.45542112,
        98.78139239, 112.07447005, 109.83421055,  78.03070386,
       105.25735462, 102.71289735,  85.23893877,  97.8789776 ,
       117.66472662, 103.47924231, 123.67594986, 100.29318097,
        90.08101996,  95.29716004, 111.70901872,  97.41420051,
        99.68503806, 103.56046083, 105.27529752, 102.91101148,
        75.29219746, 112.1530753 , 112.83679507, 113.088722  ,
        85.94730061,  85.42955875,  99.50040948,  82.45083907,
        97.78663945, 102.91155027, 101.69653646,  84.39522963,
        99.35498182, 122.42954527,  96.44552486,  85.84036009,
       114.55241228,  90.3729232 ,  88.2943061 ,  97.14556066,
       117.31330487, 106.63847805, 103.59695899,  93.96621283,
       106.50721435,  86.71881739, 140.06411757,  98.13040514,
        76.63634685,  81.15467793,  98.80097872,  95.18418974,
       105.62899411, 105.12914781, 111.28674547,  53.8387331 ,
        86.58211537, 110.91630447,  91.47730115,  92.54159047,
       100.61163537,  94.65425246, 102.46625754, 100.34892247,
        72.51872983,  90.71163683,  89.13912535,  93.1139218 ,
        92.39724695, 116.58777985,  91.58294495,  86.61882896,
       104.06413853,  96.70466534,  98.98372745,  89.42748801,
       116.19521004, 103.25165367, 101.24170653,  84.91405924,
       107.18957351,  90.63704671,  59.86626636,  99.31380872,
       102.30931074,  85.21191679,  91.66280679,  93.08590488,
        96.85212913, 107.00218569,  90.25907385, 112.60610083,
        82.99993891, 111.96418351, 115.68780652, 104.22641473,
       109.27495396, 104.38823351, 107.42499878,  83.44941373,
       102.19476356,  90.3591678 , 123.56885184, 106.85384652,
        93.88892349,  96.27372415,  97.02345538,  91.4526239 ,
        87.73173738,  91.83613703, 103.95983138,  95.84999656,
       100.62471849, 116.26174157, 113.86507799,  97.53464606,
       111.37797933, 105.71759134,  97.68501023,  90.78372667,
       127.60744053, 113.5654937 , 105.56270728, 109.39609005,
        70.35435923, 120.30351255,  84.28970269, 105.96420517,
        84.85863586, 106.38582964,  98.53664123, 100.80679303,
        88.40143631, 111.9657876 , 112.41900768, 101.04100228,
       112.99868223,  87.14153086, 124.47937551, 108.54030513,
       134.58867258, 120.71801169, 116.23765233,  95.97601517,
        92.31912221, 105.53005418, 124.87759836,  85.78683884,
        78.50833822, 101.49445176,  80.92663963, 124.42472246,
        94.68808212,  88.3500804 ,  81.47635534,  81.87762568,
       106.03904807, 106.98972836,  97.60358439,  93.73904877,
        91.39836437, 104.41289107, 103.95362849,  87.92816796,
        89.07720378,  91.00186514,  94.45447828, 122.03569465,
       124.38404074, 126.85211103, 105.30976304,  81.14500469,
       119.00967188,  92.5088747 , 101.13885967, 103.79021111,
       111.64789388, 115.95139191,  98.01569591, 120.03630573,
       123.72899485, 103.08523419,  65.89577245,  99.2803304 ,
        97.82116792,  94.31472007, 131.21695462, 125.62533964,
        88.04555758,  92.83280269,  92.76826994,  96.87225462,
       116.79372736,  89.49068371,  93.47254709,  98.1640201 ,
       110.31160442, 103.89909292, 112.88668635, 107.04693287,
       119.32619643, 103.91981093,  82.74147433,  94.76790976,
        74.53851525,  93.03786982,  95.54766347,  73.67727752,
        96.44688524, 119.05682657, 101.14512584, 106.47211059,
        95.5820634 , 102.79687326, 101.01746281, 103.20763104,
       109.9770293 ,  75.49930296, 113.30224681, 103.06651974,
       119.20068688, 111.80384334, 107.16693679,  84.9856476 ,
       102.04290707, 109.51919317, 108.47307881, 118.35341005,
        98.72326375, 106.43750892,  98.44513841,  97.37347345,
        91.12005815,  86.9498041 ,  77.28158374,  91.30608569,
       110.11772397,  91.62734053, 116.62463438, 108.76720605,
        80.56354915, 116.9435272 ,  98.65374316,  96.1239919 ,
       121.16325209, 117.56408996, 116.10584642, 115.4209386 ,
       120.51608373,  96.42530055,  93.29110199, 107.00089995,
       104.3643552 ,  67.35101776,  80.47460415, 100.09510909,
       120.59725556, 131.89878957, 126.3678545 ,  87.15747661,
        88.29881184, 113.80722109,  56.37216584,  76.88478051,
       114.58963472,  92.58059557, 102.81379146,  72.59908408,
       145.72850618, 117.34029956, 113.04292503,  87.55423737,
       102.11815665, 116.29458983,  95.8199184 ,  98.40790717,
        91.54733871, 104.58042543, 103.92252321,  93.12745571,
       107.33531256,  99.94609465,  90.67500541,  68.41195166,
       108.62497536,  90.24331427, 108.41342611,  65.00744134,
        77.64341855,  75.50580118, 107.53899017,  84.47003796,
        86.80830954,  78.95127888,  94.67057441, 104.18448961,
        93.79432186, 109.68902077, 105.1200272 ,  94.55169804,
       122.96598397, 112.5416105 , 104.56800184, 117.66538049,
       106.86530917, 111.48373185,  99.49203235, 119.30572681,
        61.29110695,  93.20082026,  92.5306097 ,  85.41559459,
       100.20528127, 119.58995747, 113.76830571,  85.64666423,
        97.42157932,  94.6487534 , 117.86039   ,  75.62439763,
        83.1563761 ,  83.68654163, 105.01111016,  84.81049961,
       106.66782373, 122.0842598 ,  95.21140146, 101.14560541,
       112.54827295, 111.45455347,  81.842145  , 104.98196239,
        98.28850682, 116.19737862, 103.84991201,  93.89098239,
       115.0375714 , 115.6636068 , 118.12280022,  74.12900124,
       100.05675426,  84.35700873,  90.62174204,  84.71253046,
       123.19623153, 106.00682386, 100.37145786,  90.53762208,
       100.23764258, 103.06218835,  88.06349493,  86.86549037,
       107.46189318,  84.52548991,  82.80569788, 122.9107244 ,
        86.45950309, 101.43210843,  93.5127417 ,  72.80454124,
        91.12953533,  73.8777489 , 109.59858534,  95.83587246,
        82.86472844, 113.62599046, 103.53277156,  91.65468609,
       110.45714869,  74.07416783,  79.34430499, 109.77012361,
        74.91924323, 123.27491737,  98.71234387, 112.44323271,
        92.8017468 ,  93.22655122,  97.97614039,  83.70918287,
        88.95786003, 103.28540539, 100.82709338, 100.85984344,
        91.08510192,  92.45100086, 112.11712572,  97.61930529,
       105.83219959, 109.55516325, 101.39117495, 111.43513238,
       103.27616585,  92.47262939,  98.47974703, 101.49070442,
       114.04748057,  94.48011116,  92.93188595,  99.90829657,
        80.21374983,  74.61498673, 115.21637014,  86.95488054,
        81.43502948,  99.62885669, 103.79707404,  86.43778574,
        99.7085349 ,  86.93489916, 103.27384236, 113.35039348,
       107.46687992, 105.66715994,  84.55643664, 101.95432469,
       102.74068715, 116.34900119, 113.42052703, 114.87579987,
       107.77279699,  79.13600442, 111.15213568,  96.73052807,
        62.03305631, 104.84102069,  92.32701984, 101.47839507,
       116.9908779 ,  79.80714962,  82.46273787, 113.62981461,
       114.69020035,  94.51138212,  96.75056075,  98.29448828,
        94.33176261,  87.03727323,  81.50313992,  86.62873789,
        78.96703227,  73.87810389, 103.66794206,  96.80702921,
       100.65504525, 114.92716378, 104.24902319,  91.73622155,
        86.78197942,  99.45205311, 105.22229136,  70.61085439,
        92.90187665, 101.81969463,  99.72380874,  99.44673842,
        62.01527279, 124.62095993, 131.86698529, 112.26161447,
       103.61089634,  91.06850394, 105.36956332,  80.75872622,
        95.34552691,  98.50633607,  86.18808364,  96.59871236,
        77.4005038 ,  79.97058598, 107.17560729, 107.66330085,
       127.76870753,  98.43544978, 101.46928078,  66.90784783,
        97.36092379,  91.41994767, 110.27250157,  87.3792269 ,
       114.64258445, 112.71600679,  76.00163543,  91.5603879 ,
       102.1677088 , 100.25325265,  96.4552227 ,  94.77518216,
        99.89028576, 117.15113027,  79.99125368,  83.41430441,
        75.76439457, 134.60554229, 116.67539958, 125.00058936,
        80.18959414,  96.44917523, 115.33318373,  95.86132042,
        80.25032137,  70.15868508, 121.46525752, 107.18863137,
       117.4966467 , 105.44898813, 105.46853683, 100.65845998,
        91.3060983 , 114.48166503, 107.23968804,  95.44729311,
        97.46606758,  88.00642371,  82.04120324, 125.90928703,
        73.8650053 , 113.23226554, 117.02543183,  80.96750359,
        77.44637877, 138.61065471,  92.47924915,  87.47047734,
       118.55346789,  69.66563621, 105.39611167, 106.96084185,
       104.54348721,  96.47704982, 107.02733852,  90.95970543,
        97.58802063,  76.96433594,  83.99957573, 110.78931075,
       125.72170704, 116.47707081,  81.32847756, 105.42685449,
        95.96606293, 103.93226779,  74.06230307,  72.73104695,
       104.4441471 , 118.43068128,  99.45706221,  90.56218106,
       109.87791408, 109.55159751, 127.90216895,  84.16684997,
       114.71697602,  91.6815975 , 105.06631358,  93.28935189,
       115.8959825 , 118.44968536,  94.55826124,  85.74296433,
       113.12654091,  86.45476626,  91.69168311,  72.91307115,
       113.97551615,  89.36015579,  90.96527393, 120.10614435,
        80.13631034,  93.30095327,  86.51218884, 110.08376944,
       103.80431303, 104.94239144,  90.01450036,  82.55486272,
       119.1758957 ,  86.16409009, 113.52882895, 103.35468603,
       116.08572612, 135.65832003,  80.71771394, 102.75522709,
       126.04735914,  81.28017549,  81.16708191, 115.60119782,
       123.73180675,  97.45427766, 100.46330533, 103.21137661,
       128.81686   ,  73.43125434,  84.87039593, 105.92189959,
        85.47776449,  99.62648103,  86.71908293, 110.45012683,
        87.93381778, 101.78668659,  99.88755925,  86.2570824 ,
       105.35547129,  98.51642851, 120.33644735, 102.57039617,
        70.78481169, 101.49134784, 132.28526441, 105.54238584,
       112.55102631, 102.38608085, 114.28131177, 119.03421032,
       125.62835278, 118.2059406 , 110.43016147, 106.55200576,
        86.76714668, 125.62746367,  88.76830087, 101.68212576,
        84.0109006 , 102.78594905,  56.68373953, 105.6420708 ,
        90.76342808, 118.75141145, 116.00262867,  93.94824182,
        80.41316531, 104.17243752, 113.9556024 , 128.00022957,
        99.75377897,  80.41275994, 112.25779   , 105.44721373,
        84.72195338,  90.96452092, 110.25532292, 101.84431232,
        72.92860517, 110.53280211,  95.73035053, 105.11602498,
        86.1579197 , 117.29154173, 103.39385304, 115.19005449,
       108.74350624,  97.76977255, 101.57527767,  98.13827332,
        99.09720058, 119.62393028, 113.25191937,  91.46982626,
       114.15464411, 118.2063989 , 103.96219431, 122.31613488,
        99.46985646, 104.88607696,  94.27190712, 108.21579727,
       103.61832544,  85.38748444,  87.9821462 , 103.58253361,
        87.91822395, 123.15043763,  89.06681846, 115.96487103,
       115.51579123,  87.80939779, 106.28243705,  82.64746561,
       121.0973466 ,  99.08048367, 118.06077443,  74.37450435,
        79.73098878, 107.49485058,  96.13642552, 101.05995706,
       148.22513578,  90.2350268 ,  95.01906579,  97.22637992,
        98.78618025,  89.69708411,  94.13571456,  91.85318072,
       101.14577209,  81.81342139,  94.22634242, 118.40549035,
        91.89989985,  91.32386277,  93.74244708,  92.36456417,
        86.90200982,  85.97581528, 122.92954909, 109.69066156,
       107.64216448,  95.67749296,  89.05001261, 122.61479015,
        72.61481178, 103.95174703, 112.2500531 , 115.77487736,
        86.08385184, 106.88190022,  98.34313295,  79.41813283,
        86.50734271,  88.0120222 , 108.48331138, 106.60217679,
        81.2943044 ,  82.31291047, 104.51970894,  78.47165525,
       111.65030659,  91.62743218,  93.23089677, 136.69732788,
       135.16576718,  92.15339277, 118.35791696,  90.44913012,
       112.5827054 ,  85.53707218,  89.54777881, 101.60996323,
        91.04393653, 108.00685635,  91.42856248,  70.43416902,
       118.5999959 ,  99.67241345, 101.57287625,  88.9541601 ,
       104.22610079,  85.07886747,  84.34862501,  88.7694246 ,
        99.83900227,  91.34643019, 102.91091076,  82.58347227,
        95.70206881, 102.38900595,  97.95504629,  97.56918546,
       106.39667781,  86.47666502,  89.38328498,  74.613302  ,
        90.93007479,  91.6213797 , 103.03643376,  94.85232988,
        98.04956845,  97.98308155, 103.71991046,  90.90561755,
       106.35573416, 110.79772905,  95.53837619,  96.70120712,
        84.48049092,  82.47644092,  97.25549784,  86.75026085,
       100.3615298 , 105.98426081, 103.55590855, 133.41607361,
        97.85251899,  87.75771732, 134.03072158,  99.33839847,
       111.09487301,  87.43989361, 110.70428886, 107.46812623,
        80.62573505, 109.78086494,  93.51032828,  81.56871742,
       118.59925673, 123.40178132,  69.24843557,  82.42380931,
       144.07714927,  85.89098297,  93.96981898,  86.97578961,
       117.43197095, 104.93619281, 101.38059763, 123.32659185,
       101.09566232,  99.34055181, 105.87380019,  87.62232951,
       108.06958598,  82.66351947, 101.86040378,  99.85627233,
        68.5655762 , 105.97506927,  82.56573834, 104.7772959 ,
       115.17044818,  87.40079953, 100.82297935,  92.95024015,
        91.35639825, 104.7185447 ,  89.21155168, 114.89979185,
       122.64003097, 123.20628311,  89.04269566, 104.37386331,
       107.66636049, 111.29442781,  93.56734695, 112.36590468,
       101.32822438,  76.78982015,  99.13196097,  95.42458476,
       122.67832996, 113.67984572, 106.15737453,  84.55499608,
       106.0020015 , 112.3871476 , 104.14667287,  93.2674513 ,
        96.4356085 ,  94.60583348, 123.43970301, 133.27696991,
       109.08424753, 135.9369006 , 123.07837756, 113.74823367,
       112.17653141,  83.51671419, 123.26965831,  95.05948482,
        80.22439803,  75.95919168, 100.43240337, 100.3811133 ,
       126.45252044, 103.41070442,  84.20001082, 110.94602946,
        99.86937232,  97.81040271,  95.81614421,  91.23918669,
       108.43729263, 108.10311578,  85.7612867 , 122.38872663,
        77.54502452,  85.87094299, 117.07128985,  84.68219633,
       105.60467338, 111.21977203, 108.85077329, 113.26377902,
        97.21665513,  94.71001402, 122.32244416, 122.00048107,
        85.59874164, 117.32324238,  56.18249684,  97.40981138,
        91.03808786, 116.52086962,  90.25409509, 124.56411658,
       113.47794108,  67.94015778,  95.88428449, 102.17723765,
        81.70216346, 109.29313509, 116.02954856,  93.76513493,
        95.67171019,  96.86419828, 118.01355398, 119.13250265,
       111.11623832, 135.16102612, 101.38987949,  70.04090685,
       112.92954737,  79.86996801,  72.59636866,  97.41991108,
       112.23785236, 107.29691543, 113.19187539, 104.76545477,
        94.32083516, 100.9913835 , 110.34014778,  92.24072516,
        89.076833  ,  68.49110592, 109.85008406, 117.15870882,
       126.44107394,  97.32367829, 109.71599154, 106.32413899,
        77.59812254,  76.36778637,  95.06181689,  85.78981991,
        89.91752716, 104.86224835,  86.56256592, 108.33327973,
        97.08850382,  97.35431735, 123.11148124,  97.51488904,
       119.59684637,  97.19205315,  87.3669975 , 113.05289883,
        99.85936235, 102.7826831 ,  97.35256467,  95.44282407,
       102.03277927, 127.13762315,  98.69905695,  89.48332799,
        88.19834565, 106.65873116,  85.95922523, 114.49456596])

Compute the **mean**, **median**, and **mode**

In [6]:
mean = np.mean(samples)
median =np.median(samples)
mode = stats.mode(samples)

In [7]:
mean

99.97241341934871

In [8]:
median

99.87846578421806

In [9]:
mode

ModeResult(mode=array([53.8387331]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [10]:
min = np.min(samples)
min

53.83873310352262

In [11]:
max = np.max(samples)
max

148.2251357775158

In [12]:
q1 = median - min
q1

46.039732680695444

In [13]:
q3 = max - median
q3

48.34666999329772

In [15]:
iqr = q3 - q1
iqr

2.3069373126022796

Compute the **variance** and **standard deviation**

In [16]:
variance = np.var(samples)
variance

212.19087751334882

In [17]:
std_dev =np.std(samples)
std_dev

14.566773064524236

Compute the **skewness** and **kurtosis**

In [ ]:
skewness =
kurtosis =

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [18]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [19]:
y = np.random.randint(x, size = 10)
y

array([ 1,  4,  6, 12,  8,  5, 11,  6, 11,  5])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [20]:
numer = len(x)*sum(x*y) - sum(x)*sum(y)
denom = np.sqrt((len(x)*sum(x**2)-sum(x)**2)*(len(y)*sum(y**2)-sum(y)**2))
r = numer/denom
r

0.40928247625406045

## Pandas Correlation Calculation

Run the code below

In [21]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [22]:
print("correlation: ", np.corrcoef(x,y))

correlation:  [[1.         0.75864029]
 [0.75864029 1.        ]]

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho =

## Seaborn Dataset Tips

Import Seaborn Library

In [23]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [24]:
tip = sns.load_dataset("tips")
tip

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [25]:
tip.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns